# -*- coding: utf-8 -*-
"""Relatório.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIsjm9fcE43EYrlxccVUB18uKxBlX49S
"""

import pandas as pd
import random




#  1. Lista de possíveis produtos
nomes_possiveis = [
    "Teclado", "Mouse", "Monitor", "Notebook", "Cabo HDMI", "Headset",
    "Impressora", "HD Externo", "SSD", "Webcam", "Microfone", "Carregador",
    "Caixa de Som", "Tablet", "Smartphone", "Pendrive"
]

#  2. Sorteia 8 produtos diferentes
produtos = random.sample(nomes_possiveis, 8)

#  3. Gera quantidades e preços aleatórios
quantidades = [random.randint(10, 100) for _ in range(8)]
precos = [round(random.uniform(5.0, 100.0), 2) for _ in range(8)]

#  4. Cria o DataFrame
df = pd.DataFrame({
    "Nome": produtos,
    "Quantidade": quantidades,
    "Preço": precos
})

#  5. Adiciona coluna "Valor Total"
df["Valor Total"] = df["Quantidade"] * df["Preço"]

#  6. Calcula produto com maior valor total
produto_maior_valor = df.loc[df["Valor Total"].idxmax()]

#  7. Calcula a média do valor total
media_valor_total = df["Valor Total"].mean()

# 8. Filtra produtos com valor total acima da média
acima_media = df[df["Valor Total"] > media_valor_total]

# 9. Exibe resultados formatados
print(" ESTOQUE COMPLETO:\n")
print(df.to_string(index=False))

print("\n PRODUTO COM MAIOR VALOR TOTAL:\n")
print(produto_maior_valor.to_string())

print(f"\n MÉDIA DO VALOR TOTAL: R$ {media_valor_total:,.2f}\n")

print("PRODUTOS COM VALOR TOTAL ACIMA DA MÉDIA:\n")
print(acima_media.to_string(index=False))
